inherit_from: .rubocop_todo.yml

# Rspec doesn't support do...end so block delimiters must be allowed
Style/BlockDelimiters:
    Exclude:
      - 'spec/**/*.rb'
Lint/AmbiguousBlockAssociation:
    Exclude:
        - 'spec/**/*.rb'
Style/PercentLiteralDelimiters:
    Exclude:
        - 'db/migrate/20200702173418_create_versions.rb'
Style/NumericLiterals:
    Exclude:
        - 'db/schema.rb'
Style/WordArray:
    Exclude:
        - 'db/schema.rb'
Style/Documentation:
    Exclude:
        - 'db/migrate/*.rb'
        # AllCops:
#     Exclude:
#         - 'db/schema.rb'

#  - Layout/EmptyLinesAroundAttributeAccessor (0.83)
#  - Layout/SpaceAroundMethodCallOperator (0.82)
#  - Lint/BinaryOperatorWithIdenticalOperands (0.89)
#  - Lint/DeprecatedOpenSSLConstant (0.84)
#  - Lint/DuplicateElsifCondition (0.88)
#  - Lint/DuplicateRescueException (0.89)
#  - Lint/EmptyConditionalBody (0.89)
#  - Lint/FloatComparison (0.89)
#  - Lint/MissingSuper (0.89)
#  - Lint/MixedRegexpCaptureTypes (0.85)
#  - Lint/OutOfRangeRegexpRef (0.89)
#  - Lint/RaiseException (0.81)
#  - Lint/SelfAssignment (0.89)
#  - Lint/StructNewOverride (0.81)
#  - Lint/TopLevelReturnWithArgument (0.89)
#  - Lint/UnreachableLoop (0.89)
#  - Style/AccessorGrouping (0.87)
#  - Style/ArrayCoercion (0.88)
#  - Style/BisectedAttrAccessor (0.87)
#  - Style/CaseLikeIf (0.88)
#  - Style/ExplicitBlockArgument (0.89)
#  - Style/ExponentialNotation (0.82)
#  - Style/GlobalStdStream (0.89)
#  - Style/HashAsLastArrayItem (0.88)
#  - Style/HashEachMethods (0.80)
#  - Style/HashLikeCase (0.88)
#  - Style/HashTransformKeys (0.80)
#  - Style/HashTransformValues (0.80)
#  - Style/OptionalBooleanParameter (0.89)
#  - Style/RedundantAssignment (0.87)
#  - Style/RedundantFetchBlock (0.86)
#  - Style/RedundantFileExtensionInRequire (0.88)
#  - Style/RedundantRegexpCharacterClass (0.85)
#  - Style/RedundantRegexpEscape (0.85)
#  - Style/SingleArgumentDig (0.89)
#  - Style/SlicingWithRange (0.83)
#  - Style/StringConcatenation (0.89)